import { chromium } from 'playwright';
const b = await chromium.launch({ headless: false });
const ctx = await b.newContext({ viewport: { width: 1400, height: 560 }, deviceScaleFactor: 2.5 });
const p = await ctx.newPage();
await p.goto('http://127.0.0.1:8801/', { waitUntil: 'load' });
await p.waitForTimeout(600);
const t0 = Date.now();
for (let i = 0; i < 10; i++) await p.screenshot({ path: `/tmp/clip${i}.png`, clip: { x: 340, y: 45, width: 720, height: 288 } });
console.log('png ms/frame', ((Date.now() - t0) / 10).toFixed(0));
const t1 = Date.now();
for (let i = 0; i < 10; i++) await p.screenshot({ path: `/tmp/clipj${i}.jpg`, type: 'jpeg', quality: 96, clip: { x: 340, y: 45, width: 720, height: 288 } });
console.log('jpg ms/frame', ((Date.now() - t1) / 10).toFixed(0));
await b.close();
