import { webkit, devices } from 'playwright';
const b = await webkit.launch();
const ctx = await b.newContext({ ...devices['iPhone 13'] });
const p = await ctx.newPage();
const errs = [];
p.on('console', (m) => { if (m.type() === 'error') errs.push(m.text().slice(0, 140)); });
p.on('pageerror', (e) => errs.push('PAGEERR ' + String(e).slice(0, 140)));
await p.goto('https://philippbogdan.com/instrumental/', { waitUntil: 'load' });
await p.waitForTimeout(1500);
await p.screenshot({ path: '/tmp/wk-landing.png', fullPage: true });
await p.tap('.demo-card[data-demo="gunnr"]');
await p.waitForTimeout(3500);
await p.screenshot({ path: '/tmp/wk-demo.png', fullPage: true });
console.log('docW', await p.evaluate(() => [document.documentElement.scrollWidth, innerWidth]));
console.log('errors:', JSON.stringify(errs));
await b.close();
