import { chromium } from 'playwright';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const p = await ctx.newPage();
const errs = [];
p.on('console', (m) => { if (m.type() === 'error') errs.push(m.text().slice(0, 120)); });
p.on('pageerror', (e) => errs.push('PAGEERR ' + String(e).slice(0, 120)));
await p.goto('https://philippbogdan.com/instrumental/', { waitUntil: 'load' });
await p.waitForTimeout(1200);
await p.tap('.demo-card[data-demo="gunnr"]');
await p.waitForTimeout(4000);
console.log('after demo tap, docW', await p.evaluate(() => document.documentElement.scrollWidth), 'innerW 390');
await p.screenshot({ path: '/tmp/inst-mob-demo.png', fullPage: true });
console.log('errors:', JSON.stringify(errs));
await b.close();
