"""
Export INSTRUMENTAL's 28 synth parameters to a Vital .vital preset file.

Uses the init.vital template from Syntheon as a base, then overwrites
the parameters we control. This ensures wavetable data and other Vital
internals are valid.
"""

import json
import math
import os
import copy

# Path to the Vital template preset (ships with Syntheon)
TEMPLATE_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "vendor", "syntheon", "syntheon", "inferencer", "vital", "init.vital"
)

# Load template once at import time
with open(TEMPLATE_PATH) as f:
    _TEMPLATE = json.load(f)


def hz_to_midi_note(hz):
    """Convert frequency in Hz to MIDI note number (continuous)."""
    if hz <= 0:
        return 0.0
    return 12.0 * math.log2(hz / 440.0) + 69.0


def params_to_vital(params_normalized, param_defs):
    """
    Convert INSTRUMENTAL's 28 normalized [0,1] params to a Vital preset dict.

    Args:
        params_normalized: list of 28 floats in [0,1]
        param_defs: list of {"name": str, "lo": float, "hi": float}

    Returns:
        dict: Complete Vital preset ready to be serialized as JSON
    """
    # Denormalize params to physical ranges
    p = {}
    for i, pd in enumerate(param_defs):
        val = params_normalized[i]
        lo, hi = pd["lo"], pd["hi"]
        p[pd["name"]] = val * (hi - lo) + lo

    # Deep copy template
    preset = copy.deepcopy(_TEMPLATE)
    s = preset["settings"]

    # --- Oscillator levels ---
    # Osc 1 = saw, Osc 2 = square/pulse, Osc 3 = sine
    s["osc_1_on"] = 1.0 if p["saw_mix"] > 0.01 else 0.0
    s["osc_1_level"] = p["saw_mix"]

    s["osc_2_on"] = 1.0 if p["square_mix"] > 0.01 else 0.0
    s["osc_2_level"] = p["square_mix"]

    s["osc_3_on"] = 1.0 if p["sine_mix"] > 0.01 else 0.0
    s["osc_3_level"] = p["sine_mix"]

    # --- Noise (via sample section or add to osc levels) ---
    noise_total = p["noise_mix"] + p["noise_floor"]
    s["sample_on"] = 1.0 if noise_total > 0.01 else 0.0
    s["sample_level"] = min(1.0, noise_total * 2.0)  # scale 0-0.5 to 0-1

    # --- Detune ---
    s["osc_1_transpose"] = p["detune"]
    s["osc_2_transpose"] = p["detune"]
    s["osc_3_transpose"] = p["detune"]

    # --- Unison ---
    n_voices = max(1, round(p["unison_voices"]))
    for osc in ["osc_1", "osc_2", "osc_3"]:
        s[f"{osc}_unison_voices"] = float(n_voices)
        s[f"{osc}_unison_detune"] = p["unison_spread"] * 20.0  # Vital uses larger scale

    # --- Pulse width (osc 2 wave frame) ---
    s["osc_2_wave_frame"] = p["pulse_width"]

    # --- Filter ---
    s["filter_1_on"] = 1.0
    s["filter_1_cutoff"] = hz_to_midi_note(p["filter_cutoff"])
    s["filter_1_resonance"] = p["filter_resonance"]
    s["filter_1_mix"] = 1.0

    # Filter slope -> model (0=analog 12dB, 1=analog 24dB, 2=dirty, etc.)
    slope = p["filter_slope"]
    if slope < 18:
        s["filter_1_model"] = 0.0  # 12 dB/oct
    elif slope < 36:
        s["filter_1_model"] = 1.0  # 24 dB/oct
    else:
        s["filter_1_model"] = 6.0  # Steep

    # --- Amplitude envelope (env 1) ---
    s["env_1_attack"] = p["attack"]
    s["env_1_decay"] = p["decay"]
    s["env_1_sustain"] = p["sustain"]
    s["env_1_release"] = p["release"]

    # --- Filter envelope (env 2) ---
    s["env_2_attack"] = p["filter_attack"]
    s["env_2_decay"] = p["filter_decay"]
    s["env_2_sustain"] = p["filter_sustain"]
    s["env_2_release"] = p["filter_release"]

    # --- Filter envelope amount (modulation routing) ---
    # Vital uses a modulations array for routing
    filter_env_amount = p["filter_env"]
    if abs(filter_env_amount) > 0.01:
        mod_entry = {
            "source": "env_2",
            "destination": "filter_1_cutoff",
            "amount": filter_env_amount * 0.5  # scale down, Vital mods are sensitive
        }
        if "modulations" not in preset:
            preset["modulations"] = []
        preset["modulations"].append(mod_entry)

    # --- Master gain ---
    s["volume"] = p["gain"]

    # --- Reverb ---
    s["reverb_on"] = 1.0 if p["reverb_mix"] > 0.01 else 0.0
    s["reverb_dry_wet"] = p["reverb_mix"]
    s["reverb_size"] = p["reverb_size"]

    # --- EQ ---
    s["eq_on"] = 1.0
    s["eq_low_cutoff"] = hz_to_midi_note(p["eq1_freq"])
    s["eq_low_gain"] = p["eq1_gain"]
    s["eq_high_cutoff"] = hz_to_midi_note(p["eq2_freq"])
    s["eq_high_gain"] = p["eq2_gain"]

    # --- Metadata ---
    preset["preset_name"] = "INSTRUMENTAL Match"
    preset["author"] = "INSTRUMENTAL"
    preset["comments"] = "Auto-generated by INSTRUMENTAL (inverse synthesis)"

    return preset


def write_vital_preset(params_normalized, param_defs, output_path):
    """Generate and write a .vital preset file."""
    preset = params_to_vital(params_normalized, param_defs)
    with open(output_path, "w") as f:
        json.dump(preset, f, indent=2)
    return output_path
